### ISSUE TITLE
something is broken.

### ISSUE THREAD

**Issue by iMu7aMMaD** [stefmmm/MCSS-Panel#6]
Uncaught (in promise) Error: Request failed with status code 404.

**Comment by PouletteMC** [comment]
when does that happen ? we need more info to fix the issue

**Comment by stefmmm** [comment]
yeah we are indeed gonna need more info, please provide the full url of the page you're on when that happens, also provide the url that is returning that 404 error.

**Comment by iMu7aMMaD** [comment]
![Here](https://user-images.githubusercontent.com/69051329/121914384-80544f80-cd32-11eb-9349-4f8ee71b11b0.png)

**Comment by PouletteMC** [comment]
Is MCSS running on the same machine ?

Also I think the latest dev build was only released to MVPs and above, an out fixes the first error. Will send it to you on discord when I get home

**Comment by stefmmm** [comment]
This issue is caused by the API not having the proper CORS header, this was fixed in a mcss dev build which can be found on the mcss discord server in the #devbuilds channel, since this issue is not related to the panel itself we can't do much besides suggesting you use the dev build till the API is available in a full mcss release, so i'll be closing this issue, feel free to reopen it if something arises.

**Comment by iMu7aMMaD** [comment]
but I do have the dev build, yet still the same thing happens.

**Comment by PouletteMC** [comment]
There's more than one

**Comment by iMu7aMMaD** [comment]
where can I find the link?

**Comment by iMu7aMMaD** [comment]
I have the one @Fiahblade send in the Discord #devbuilds channel.

**Comment by PouletteMC** [comment]
I told you I would send it to you when I got home

**Comment by iMu7aMMaD** [comment]
okay
